version: '3.8'

services:
  go:
    container_name: go-container
    build:
      context: ./golang
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    # environment:
    #   - CHANNEL_ID
    #   - CHANNEL_SECRET
    #   - AWS_ACCESS_KEY_ID
    #   - AWS_SECRET_ACCESS_KEY
    #   - IAM_ROLE_NAME
    #   - IAM_ROLE_ID
    #   - GPT_KEY
    #   - PEXELS_API_KEY
    #   - P_ALG
    #   - P_D
    #   - P_DP
    #   - P_DQ
    #   - P_E
    #   - P_KTY
    #   - P_N
    #   - P_P
    #   - P_Q
    #   - P_QI
    #   - PH_TYP
    #   - PH_KID
    #   - PRODUCTION
    ports:
      - 8080:8080
      # - 8081:8081
    tty: true
    volumes:
      - type: bind
        source: ./golang/src
        target: /go/src
 
