version: '3.8'

services:
  go:
    container_name: go-container
    build:
      context: ./golang
      dockerfile: Dockerfile.dev
    environment:
      - CHANNEL_SECRET
      - CHANNEL_ACCESS_TOKEN
      - S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY
      - GPT_KEY
      - PEXELS_API_KEY
      - P_ALG
      - P_D
      - P_DP
      - P_DQ
      - P_E
      - P_KTY
      - P_N
      - P_P
      - P_Q
      - P_QI
      - PH_TYP
      - PH_KID
    ports:
      - 8080:8080
      # - 8081:8081
    tty: true
    volumes:
      - type: bind
        source: ./golang/src
        target: /go/src
 
